### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by marecl** [marecl/boxmoduino#1]
- [ ] Ohmmeter

- [ ] 5click lock and unlock

- [ ] More accurate Vin measurements

- [ ] Minimize parts

- [ ] Optimize code

- [ ] Use another display than HD77480

- [ ] DO NOT use global functions

**Comment by Vinzgore** [comment]
Changing the MOSFET’s pin PWM frequency is pretty easy (see [this](http://playground.arduino.cc/Code/PwmFrequency)) but keep in mind it will alter the behaviour of `millis()` and other time based functions.  
I recommend you take a look at [this link](http://playground.arduino.cc/Main/TimerPWMCheatsheet) to see the workaround.

**Comment by marecl** [comment]
I found this library which will save me a lot of work, but I will need to edit other libs as well.  
http://playground.arduino.cc/Code/Prescaler
